packages:
  - "."

confirmModulesPurge: false
verifyDepsBeforeRun: false

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

minimumReleaseAgeExclude:
  - '@uiw/codemirror-extensions-basic-setup@4.25.10'
  - '@uiw/react-codemirror@4.25.10'
