name = "go-nav"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "go-nav-data"
database_id = "9bf1ae00-511a-404f-934d-283aa27f51de"

[[r2_buckets]]
binding = "UPLOADS_BUCKET"
bucket_name = "go-nav-uploads"

[vars]
STORAGE_DRIVER = "cloudflare"
